---
name: Z-Wave JS UI 3
version: dev
slug: zwave_js_ui_3
description: Fully configurable Z-Wave JS gateway and control panel
url: https://github.com/hassio-addons/app-zwave-js-ui
ingress: true
ingress_stream: true
panel_title: Z-Wave JS 3
panel_icon: mdi:z-wave
startup: system
init: false
timeout: 30
arch:
  - aarch64
  - amd64
discovery:
  - zwave_js
services:
  - mqtt:want
uart: true
udev: true
map:
  - share:rw
ports:
  3000/tcp: null
ports_description:
  3000/tcp: Z-Wave JS communication
